version: '3.9'

services:
  file-api:
    container_name: file-api
    image: edgeai/file-api:${TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile_${TAG:-develop}
    networks:
      - edgeai-net
      - kong-net
    ports:
      - "9003:9003/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  edgeai-net:
    name: edgeai-net
    external: false
  kong-net:
    name: kong-net
    external: false
